name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Junit tests
        run: ./bld compile
        # TODO requires JUnit 5
#      - name: Run Junit tests
#        run: ./bld test